### ISSUE TITLE
Insufficent memory

### ISSUE THREAD

**Issue by tak2hu** [pixelomer/BadApple#2]
I compiled badapple.bin on linux and when `upload_data.py badapple.bin` I got this error
```
Traceback (most recent call last):
  File "/home/kys/Projects/pongoosstuff/PongoOS/scripts/upload_data.py", line 35, in <module>
    dev.write(2,data,1000000)
  File "/usr/lib/python3.10/site-packages/usb/core.py", line 989, in write
    return fn(
  File "/usr/lib/python3.10/site-packages/usb/backend/libusb1.py", line 837, in bulk_write
    return self.__write(self.lib.libusb_bulk_transfer,
  File "/usr/lib/python3.10/site-packages/usb/backend/libusb1.py", line 938, in __write
    _check(retval)
  File "/usr/lib/python3.10/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 12] Insufficient memory
```

**Comment by tak2hu** [comment]
Nvm using pongoterm works with `/send`
